=== meilanperez/CODE-WORKSPACE/Netflix.dtd
<!ELEMENT NETFLIX (Catalogo,Usuarios)>
<!ENTITY plataforma "Netflix España"> 
<!ELEMENT Catalogo (Series,Peliculas)>
<!ELEMENT Series (Titulo+)>
<!ELEMENT Peliculas (Titulo+)>
<!ELEMENT Titulo (Director,Sinopsis?,Episodios?,Reparto?)>
<!ATTLIST Titulo 
  id ID #REQUIRED
  nombre CDATA #REQUIRED
  año CDATA #REQUIRED
  genero CDATA #REQUIRED
  categoria CDATA #REQUIRED
  ageRating CDATA #REQUIRED
  temporadas CDATA #IMPLIED
>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Sinopsis (#PCDATA)>

<!ELEMENT Episodios (Episodio+)>
<!ELEMENT Episodio (#PCDATA)>
<!ATTLIST Episodio 
  numero  CDATA #REQUIRED
  duracion  CDATA #IMPLIED
>
<!ELEMENT Reparto (Actor+)>
<!ELEMENT Actor (#PCDATA)>
<!ATTLIST Actor
    rol (Protagonista|Secundario|Cameo) #REQUIRED 
    personaje CDATA #REQUIRED
>

<!ELEMENT Usuarios (Usuario+)>
<!ELEMENT Usuario (Nombre, Edad, Email?)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Edad (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== meilanperez/CODE-WORKSPACE/Netflix.xml
<?xml version="1.0">
<!DOCTYPE NETFLIX SYSTEM "Netflix.dtd">
<NETFLIX>
 <Catalogo>
  <Series>
   <Titulo id="S1" nombre="Los Bridgerton" año="2026" genero="Romance" categoria="Drama" ageRating="+18" temporadas="3">
   <Director>Chris Van Dusen</Director>
   <Sinopsis> Drama romántico ambientado en la alta sociedad londinense</Sinopsis>
   <Episodios>
    <Episodio numero="1">Diamante de la temporada</Episodio>
   </Episodios>
   </Titulo>
   <Titulo id="S2" nombre="Stranger Code" año="2024" genero="Ciencia Ficcion" categoria="Suspenso" ageRating="+16" temporadas="2">
   <Director>Ana Torres</Director>
   <Sinopsis>Un grupo de jóvenes descubre una red secreta digital. </Sinopsis>
   <Episodios>
    <Episodio numero="1">El mensaje oculto</Episodio>
   </Episodios>
   </Titulo>
</Series>
<Peliculas>
 <Titulo id="p1" nombre="El Botin" año="2026" genero="Accion" categoria="Drama" ageRating="+16">
  <Director>Carlos Ruiz</Director>
  <Reparto>
   <Actor rol="Protagonista" personaje="Miguel">Juan Perez</Actor>
   <Actor rol="Secundario" personaje="Laura">Ana Lopez</Actor>
  </Reparto>
 </Titulo>
 <Titulo id="p2" nombre="My Oxford Year" año="2015" genero="Romance" categoria="Drama" ageRating="+12">
  <Director>Rachel Smith</Director>
  <Reparto>
   <Actor rol="Protagonista" personaje="Sophie">Emily Clark</Actor>
  </Reparto>
 </Titulo>
</Peliculas>
 </Catalogo>
<Usuarios>
<Usuario id="U1">
 <Nombre>Meilan</Nombre>
 <Edad>22</Edad>
 <Email>meilan@gmail.com</Email>
</Usuario>
</Usuarios>
</NETFLIX>
